// <auto-generated />
using DL91;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL91.Migrations
{
    [DbContext(typeof(DB91Context))]
    [Migration("20220207054650_db4")]
    partial class db4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("DL91.DB91", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsImgDownload");

                    b.Property<string>("imgUrl");

                    b.Property<int>("isLike");

                    b.Property<int>("isVideoDownloaded");

                    b.Property<int>("time");

                    b.Property<string>("title");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("DB91s");
                });

            modelBuilder.Entity("DL91.DBCfg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("isRuning");

                    b.Property<int>("maxID");

                    b.HasKey("id");

                    b.ToTable("DBCfgs");
                });
#pragma warning restore 612, 618
        }
    }
}
