// <auto-generated />
using DL91;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL91.Migrations
{
    [DbContext(typeof(DB91Context))]
    partial class DB91ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("DL91.DB91", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsImgDownload");

                    b.Property<string>("imgUrl");

                    b.Property<bool>("isHD");

                    b.Property<int>("isLike");

                    b.Property<int>("isVideoDownloaded");

                    b.Property<int>("time");

                    b.Property<string>("title");

                    b.Property<int>("typeId");

                    b.Property<string>("url");

                    b.Property<long>("videoFileSize");

                    b.HasKey("id");

                    b.ToTable("DB91s");
                });

            modelBuilder.Entity("DL91.DBCfg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("blockKeyWord");

                    b.Property<int>("isRuning");

                    b.HasKey("id");

                    b.ToTable("DBCfgs");
                });

            modelBuilder.Entity("DL91.DBType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("count");

                    b.Property<int>("maxID");

                    b.Property<string>("name");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("DBTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
